// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpgUrPdQWqQWbFx9ox7MX0F4AG8C0k_RI',
    appId: '1:1056364468324:web:c255861e913c846c2aa771',
    messagingSenderId: '1056364468324',
    projectId: 'tiktok-ec59d',
    authDomain: 'tiktok-ec59d.firebaseapp.com',
    databaseURL: 'https://tiktok-ec59d-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-ec59d.firebasestorage.app',
    measurementId: 'G-4MNMP8RHRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDetlUc4NiQFZjAJOuuS9vrwnqraWsOzpo',
    appId: '1:1056364468324:android:ff8c0c6a59dce0ea2aa771',
    messagingSenderId: '1056364468324',
    projectId: 'tiktok-ec59d',
    databaseURL: 'https://tiktok-ec59d-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-ec59d.firebasestorage.app',
  );
}
